import { Plane, Wallet } from "lucide-vue-next";

const urls = {
  KEYS: {
    GET: "get",
    POST: "post",
    PUT: "put",
    PATCH: "patch",
    DELETE: "delete",
  },
  auth: {
    login: "/login",
    profile: "/profile",
  },
  dashboard: {
    list: "/dashboard",
    revenueAnalytics: "/dashboard/revenue-analytics",
  },
  tradingAccounts: {
    list: "/accounts",
    create: "/accounts/create",
    changePassword: "/accounts/change-password",
    accountTrades: "/accounts/trades",
    transactions: "/accounts/transactions",
    deposit: "/accounts/deposit",
    withdraw: "/accounts/withdraw",
    groups: "/account-groups",
    export: "/export/accounts/export",
  },
  clientList: {
    list: "/client-list",
    changeIB: "/client/change-ib",
    changeStatus: "/users/status",
    update: "/client/update",
    createIB: "/create-ib",
    create: "/client/create",
    delete: "/clients",
    updateReferralLink: "/clients/referral-link",
    export: "/export/client-list/export",
  },
  clientLedger: {
    list: "/ledger/clients",
    allClients: "/search/clients",
    allAccounts: "/search/accounts",
    internalTransfers: "/ledger/internal-transfers",
    export: "/export/clients-ledger/export",
  },
  fmLedger: {
    list: "/ledger/fms",
    allFundManagers: "/search/fm",
    export: "/export/fm-ledger/export",
  },
  ibLedger: {
    list: "/ledger/ib",
    allIbs: "/search/ib",
    update: "/ledger/ib/update",
    export: "/export/ledger/ib/export",
  },
  adminLedger: {
    list: "/ledger/admin",
    export: "/export/platform-ledger/export",
  },
  ibTree: {
    list: "/ib-network",
    create: "/ib/create",
    update: "/ib/update",
    delete: "/ib/delete",
    transfer: "/ib-transfer",
    clients: "/ibs/clients/",
    export: "/export/ib-network/export",
  },
  referralLinks: {
    list: "/ibs/referral-links",
    create: "/ibs/referral-links",
    update: "/referral-links",
  },
  auditLogs: {
    list: "/audit-logs",
    export: "/export/audit-logs",
  },
  fm: {
    list: "/fund_managers",
    create: "/fund_managers/create",
    edit: "/fund_managers/edit",
    requestList: "/fm/requests",
    acceptRequest: "/fm/requests/approve",
    rejectRequest: "/fm/requests/reject",
    settlementPreview: "/settlement/preview",
    settlementRun: "/settlement/run",
    export: "/export/fund_managers/export",
    exportFMRequest: "/export/fm/requests/export",
  },
  settlements: {
    list: "/settlements",
    trades: "/settlements/trades",
    export: "/export/settlements/export",
  },
  tickets: {
    list: "/support/tickets",
    create: "/support/tickets",
    detail: "/support/tickets",
    comment: "/support/tickets/comments",
    attachment: "/support/tickets/attachments",
    updateStatus: "/support/tickets/status",
    export: "/export/tickets/export",
  },
  platformTickets: {
    list: "/support/tickets/platform",
    create: "/support/tickets",
    detail: "/support/tickets",
    comment: "/support/tickets/comments",
    attachment: "/support/tickets/attachments",
    updateStatus: "/support/tickets/status",
    export: "/export/tickets/platform/export",
  },
  groupConfig: {
    list: "/mt5/groups",
    add: "/group-config",
    setDefault: "/broker-group-configs/default",
    deconfig: "/group-config/",
    categories: "/account-categories",
    groups: "/mt5/groups",
    create: "/group-config",
  },
  paymentMethods: {
    create: "/payments/payment-methods",
    list: "/payments/payment-methods",
    syncWallets: "/payments/sync-wallets",
    update: "/payments/payment-methods",
  },
  paymentRequests: {
    list: "/payment-requests",
    approve: "/payment-requests/approve/",
    reject: "/payment-requests/reject/",
    export: "/export/payment-requests/export",
  },
  emailSettings: {
    details: "/email-settings",
    update: "/email-settings",
  },
  emailTemplates: {
    list: "/email-templates",
    details: "/email-templates",
    create: "/email-templates",
    update: "/email-templates",
    manual: "/emails/manual/send",
  },
  integrations: {
    list: "/company-integrations",
    create: "/company-integrations",
    update: "/company-integrations",
    run: "/company-integrations/run",
  },
  rbac: {
    roles: {
      list: "/rbac/roles",
      create: "/rbac/roles",
      update: "/rbac/roles",
      delete: "/rbac/roles",
      permissions: "/rbac/permissions",
      assignPermissions: "/rbac/roles/permissions",
    },
    staff: {
      list: "/rbac/users",
      create: "/rbac/users",
      updateRole: "/rbac/users/role",
      updateStatus: "/rbac/users/status",
      delete: "/rbac/users",
    },
    userPermissions: {
      me: "/rbac/me/permissions",
      all: "/rbac/permissions",
      manage: "/rbac/users/permissions",
    },
    resources: {
      list: "/rbac/resources",
      create: "/rbac/resources",
      update: "/rbac/resources",
      delete: "/rbac/resources",
    },
    actions: {
      list: "/rbac/actions",
      create: "/rbac/actions",
      update: "/rbac/actions",
      delete: "/rbac/actions",
    },
    permissionsMapping: {
      list: "/rbac/permissions_mapping",
      create: "/rbac/permissions_mapping",
      delete: "/rbac/permissions_mapping",
    },
  },
  myWallets: {
    export: " /fm/requests/export",
  },
};

export default urls;
