import { Plane, Wallet } from "lucide-vue-next";

const urls = {
  KEYS: {
    GET: "get",
    POST: "post",
    PUT: "put",
    PATCH: "patch",
    DELETE: "delete",
  },
  auth: {
    login: "/login",
    profile: "/profile",
    updateProfile: "/user/update_profile",
  },
  dashboard: {
    list: "/dashboard",
    accounts: "/live-user-count",
    revenueAnalytics: "/dashboard/revenue-analytics",
    liveUsers: "/live-users",
  },
  tradingAccounts: {
    list: "/accounts",
    create: "/accounts/create",
    changePassword: "/accounts/change-password",
    changeBrokerGroup: "/accounts/change-broker-group",
    accountTrades: "/accounts/trades",
    transactions: "/accounts/transactions",
    deposit: "/accounts/deposit",
    withdraw: "/accounts/withdraw",
    groups: "/account-groups",
    toggleTrading: "/account/toggle-trading",
    transactionRestrictions: (tradingAccountId) =>
      `/trading-accounts/${tradingAccountId}/transaction-restrictions`,
  },
  clientList: {
    list: "/client-list",
    changeIB: "/client/change-ib",
    changeStatus: "/users/status",
    update: "/client/update",
    createIB: "/create-ib",
    create: "/client/create",
    delete: "/clients",
    updateReferralLink: "/clients/referral-link",
    userDashboard: "/user-dashboard",
  },
  clientDepth: {
    overview: "/overview",
    kyc: "/user/kyc-details",
  },
  clientLedger: {
    list: "/ledger/clients",
    allClients: "/search/clients",
    allAccounts: "/search/accounts",
    internalTransfers: "/ledger/internal-transfers",
  },
  fmLedger: {
    list: "/ledger/fms",
    allFundManagers: "/search/fm",
  },
  ibLedger: {
    list: "/ledger/ib",
    allIbs: "/search/ib",
    update: "/ledger/ib/update",
  },
  adminLedger: {
    list: "/ledger/admin",
  },
  ibTree: {
    list: "/ib-network",
    create: "/ib/create",
    update: "/ib/update",
    delete: "/ib/delete",
    transfer: "/ib-transfer",
    clients: "/ibs/clients/",
  },
  referralLinks: {
    list: "/ibs/referral-links",
    create: "/ibs/referral-links",
    update: "/referral-links",
  },
  auditLogs: {
    list: "/audit-logs",
  },
  fm: {
    list: "/fund_managers",
    create: "/fund_managers/create",
    edit: "/fund_managers/edit",
    requestList: "/fm/requests",
    acceptRequest: "/fm/requests/approve",
    rejectRequest: "/fm/requests/reject",
    settlementPreview: "/settlement/preview",
    settlementRun: "/settlement/run",
    offers: "/fund_managers/offers",
    followers: "/fund_managers/followers",
    followersDetails: "fund_managers/followers/info/",
    editFollower: "/fund_managers/followers/edit",
    offerJoinLinks: "/fund_managers/offers/join-links",
    offerAgents: "/fund_managers/offers/agents",
  },
  tradeBook: {
    filters: "/trade-book/filters",
    followerDetails: "/trade-book/followers/",
    masterTrades: "/trade-book/master-trades",
    positions: "/trade-book/positions",
    orders: "/trade-book/orders",
    deals: "/trade-book/deals",
  },
  fmOffers: {
    list: "/offers",
    create: "/offers",
    joinLinks: "/offers/join-links",
    agents: "/offers/agents",
  },
  settlements: {
    list: "/settlements",
    trades: "/settlements/trades",
  },
  tickets: {
    list: "/support/tickets",
    create: "/support/tickets",
    detail: "/support/tickets",
    comment: "/support/tickets/comments",
    addComment: "/support/tickets/comments",
    attachment: "/support/tickets/attachments",
    addAttachment: "/support/tickets/attachments",
    updateStatus: "/support/tickets/status",
    assign: "/support/tickets/assign",
  },
  platformTickets: {
    list: "/support/tickets/platform",
    create: "/support/tickets",
    createAdminTicket: "/support/admin/tickets",
    detail: "/support/tickets",
    comment: "/support/tickets/comments",
    addComment: "/support/tickets/comments",
    attachment: "/support/tickets/attachments",
    addAttachment: "/support/tickets/attachments",
    updateStatus: "/support/tickets/status",
    assign: "/support/tickets/assign",
  },
  groupConfig: {
    list: "/mt5/groups",
    add: "/group-config",
    setDefault: "/broker-group-configs/default",
    deconfig: "/group-config/",
    categories: "/account-categories",
    groups: "/mt5/groups",
    create: "/group-config",
  },
  paymentMethods: {
    create: "/payments/payment-methods",
    list: "/payments/payment-methods",
    syncWallets: "/payments/sync-wallets",
    update: "/payments/payment-methods",
  },
  currencyRates: {
    list: "/payments/currency-rates",
    create: "/payments/currency-rates",
    update: "/payments/currency-rates",
    delete: "/payments/currency-rates",
  },
  paymentRequests: {
    list: "/payment-requests",
    approve: "/payment-requests/approve/",
    reject: "/payment-requests/reject/",
  },
  paymentGatewayData: {
    list: "/payment-gateway-data",
  },
  paymentSettings: {
    bulkRestrictions: "/clients/transaction-restrictions/bulk",
  },
  emailSettings: {
    details: "/email-settings",
    update: "/email-settings",
  },
  emailTemplates: {
    list: "/email-templates",
    details: "/email-templates",
    create: "/email-templates",
    update: "/email-templates",
    manual: "/emails/manual/send",
  },
  emailLogs: {
    list: "/fetch-logs",
    sync: "/emails/sync-events/campaign",
    // sync: "/emails/sync-events",
    tags: "/filter-template-codes",
    viewLogDetails: "/emails/preview",
    logDetails: "/fetch/dispatch/records/campaign",
    // logList: "/fetch/dispatch/records",
    logList: "/fetch/dispatch/tags",
    sendMail: "/emails/campaigns/resend",
  },
  integrations: {
    list: "/company-integrations",
    create: "/company-integrations",
    update: "/company-integrations",
    run: "/company-integrations/run",
  },
  telegram: {
    list: "/get-bots",
    create: "/addbot",
    update: "/update-bot",
    run: "/company-integrations/run",
    delete: "/delete-bot",
  },
  telegram_config: {
    list: "/get/configrations",
    create: "/create/update/settings",
    update: "/update/configrations",
    run: "/company-integrations/run",
    delete: "/delete-bot",
  },
  rbac: {
    roles: {
      list: "/rbac/roles",
      create: "/rbac/roles",
      update: "/rbac/roles",
      delete: "/rbac/roles",
      permissions: "/rbac/permissions",
      assignPermissions: "/rbac/roles/permissions",
    },
    staff: {
      list: "/rbac/users",
      create: "/rbac/users",
      updateRole: "/rbac/users/role",
      updateStatus: "/rbac/users/status",
      delete: "/rbac/users",
      resetPassword: "/rbac/users/reset-password",
    },
    userPermissions: {
      me: "/rbac/me/permissions",
      all: "/rbac/permissions",
      manage: "/rbac/users/permissions",
    },
    resources: {
      list: "/rbac/resources",
      create: "/rbac/resources",
      update: "/rbac/resources",
      delete: "/rbac/resources",
    },
    actions: {
      list: "/rbac/actions",
      create: "/rbac/actions",
      update: "/rbac/actions",
      delete: "/rbac/actions",
    },
    permissionsMapping: {
      list: "/rbac/permissions_mapping",
      create: "/rbac/permissions_mapping",
      delete: "/rbac/permissions_mapping",
    },
  },
  notifications: {
    create: "/notifications/create",
    update: "/notifications",
    adminList: "/notifications/list",
    myNotifications: "/notifications/my-notifications",
    markRead: "/notifications/read",
    send: "/notifications/send",
    readStatus: "/notifications/read-status",
  },
  media: {
    groups: {
      list: "/media-groups",
      create: "/create-media-group",
      update: "/update-media-group",
      delete: "/delete-media-group",
    },
    images: {
      list: "/media-images",
      create: "/create-media-image",
      update: "/media-images",
      delete: "/media-images",
    },
  },
  lead: {
    list: "/lead/",
    detail: "/lead/",
    assign: "/lead/assign/",
    history: "/lead/history/",
    dashboard: "/lead/dashboard",
    stages: "/lead/stage",
    export: "/lead/export",
    importTemplate: "/lead/import/template",
    import: "/lead/import",
    tags: "/lead/",
    bulkTags: "/lead/tags/bulk",
  },
  tags: {
    list: "/tags",
    search: "/tags",
    limits: "/tags/limits",
    create: "/tags",
    byId: (id) => `/tags/${id}`,
    update: (id) => `/tags/${id}`,
    activate: (id) => `/tags/${id}/activate`,
    deactivate: (id) => `/tags/${id}/deactivate`,
    delete: (id) => `/tags/${id}`,
    assignments: (type, id) => `/tags/assignments/${type}/${id}`,
    removeAssignment: (type, id, tagId) =>
      `/tags/assignments/${type}/${id}/${tagId}`,
    bulkAssignments: (type) => `/tags/assignments/${type}/bulk`,
    leadTags: (leadId) => `/lead/${leadId}/tags`,
    removeLeadTag: (leadId, tagId) => `/lead/${leadId}/tags/${tagId}`,
    leadBulk: "/lead/tags/bulk",
    userTags: (userId) => `/users/${userId}/tags`,
    removeUserTag: (userId, tagId) => `/users/${userId}/tags/${tagId}`,
    userBulk: "/users/tags/bulk",
  },
  watchlist: {
    settings: "/watchlist/settings",
    symbols: "/watchlist/symbols",
    symbolDetail: (id) => `/watchlist/symbols/${id}`,
    import: "/watchlist/symbols/import",
    template: "/watchlist/symbols/template",
  },
};

export default urls;
