// Standard country list with flag emojis
export const countries = [
 { value: 'AF', label: 'AF (Afghanistan)' , flagCode: 'af' },
 { value: 'AL', label: 'AL (Albania)' , flagCode: 'al' },
 { value: 'DZ', label: 'DZ (Algeria)' , flagCode: 'dz' },
 { value: 'AD', label: 'AD (Andorra)' , flagCode: 'ad' },
 { value: 'AO', label: 'AO (Angola)' , flagCode: 'ao' },
 { value: 'AR', label: 'AR (Argentina)' , flagCode: 'ar' },
 { value: 'AM', label: 'AM (Armenia)' , flagCode: 'am' },
 { value: 'AU', label: 'AU (Australia)' , flagCode: 'au' },
 { value: 'AT', label: 'AT (Austria)' , flagCode: 'at' },
 { value: 'AZ', label: 'AZ (Azerbaijan)' , flagCode: 'az' },
 { value: 'BS', label: 'BS (Bahamas)' , flagCode: 'bs' },
 { value: 'BH', label: 'BH (Bahrain)' , flagCode: 'bh' },
 { value: 'BD', label: 'BD (Bangladesh)' , flagCode: 'bd' },
 { value: 'BY', label: 'BY (Belarus)' , flagCode: 'by' },
 { value: 'BE', label: 'BE (Belgium)' , flagCode: 'be' },
 { value: 'BZ', label: 'BZ (Belize)' , flagCode: 'bz' },
 { value: 'BJ', label: 'BJ (Benin)' , flagCode: 'bj' },
 { value: 'BT', label: 'BT (Bhutan)' , flagCode: 'bt' },
 { value: 'BO', label: 'BO (Bolivia)' , flagCode: 'bo' },
 { value: 'BA', label: 'BA (Bosnia and Herzegovina)' , flagCode: 'ba' },
 { value: 'BW', label: 'BW (Botswana)' , flagCode: 'bw' },
 { value: 'BR', label: 'BR (Brazil)' , flagCode: 'br' },
 { value: 'BN', label: 'BN (Brunei)' , flagCode: 'bn' },
 { value: 'BG', label: 'BG (Bulgaria)' , flagCode: 'bg' },
 { value: 'BF', label: 'BF (Burkina Faso)' , flagCode: 'bf' },
 { value: 'BI', label: 'BI (Burundi)' , flagCode: 'bi' },
 { value: 'KH', label: 'KH (Cambodia)' , flagCode: 'kh' },
 { value: 'CM', label: 'CM (Cameroon)' , flagCode: 'cm' },
 { value: 'CA', label: 'CA (Canada)' , flagCode: 'ca' },
 { value: 'CL', label: 'CL (Chile)' , flagCode: 'cl' },
 { value: 'CN', label: 'CN (China)' , flagCode: 'cn' },
 { value: 'CO', label: 'CO (Colombia)' , flagCode: 'co' },
 { value: 'CR', label: 'CR (Costa Rica)' , flagCode: 'cr' },
 { value: 'HR', label: 'HR (Croatia)' , flagCode: 'hr' },
 { value: 'CU', label: 'CU (Cuba)' , flagCode: 'cu' },
 { value: 'CY', label: 'CY (Cyprus)' , flagCode: 'cy' },
 { value: 'CZ', label: 'CZ (Czechia)' , flagCode: 'cz' },
 { value: 'DK', label: 'DK (Denmark)' , flagCode: 'dk' },
 { value: 'DJ', label: 'DJ (Djibouti)' , flagCode: 'dj' },
 { value: 'DM', label: 'DM (Dominica)' , flagCode: 'dm' },
 { value: 'DO', label: 'DO (Dominican Republic)' , flagCode: 'do' },
 { value: 'EC', label: 'EC (Ecuador)' , flagCode: 'ec' },
 { value: 'EG', label: 'EG (Egypt)' , flagCode: 'eg' },
 { value: 'SV', label: 'SV (El Salvador)' , flagCode: 'sv' },
 { value: 'EE', label: 'EE (Estonia)' , flagCode: 'ee' },
 { value: 'SZ', label: 'SZ (Eswatini)' , flagCode: 'sz' },
 { value: 'ET', label: 'ET (Ethiopia)' , flagCode: 'et' },
 { value: 'FJ', label: 'FJ (Fiji)' , flagCode: 'fj' },
 { value: 'FI', label: 'FI (Finland)' , flagCode: 'fi' },
 { value: 'FR', label: 'FR (France)' , flagCode: 'fr' },
 { value: 'GA', label: 'GA (Gabon)' , flagCode: 'ga' },
 { value: 'GM', label: 'GM (Gambia)' , flagCode: 'gm' },
 { value: 'GE', label: 'GE (Georgia)' , flagCode: 'ge' },
 { value: 'DE', label: 'DE (Germany)' , flagCode: 'de' },
 { value: 'GH', label: 'GH (Ghana)' , flagCode: 'gh' },
 { value: 'GR', label: 'GR (Greece)' , flagCode: 'gr' },
 { value: 'GD', label: 'GD (Grenada)' , flagCode: 'gd' },
 { value: 'GT', label: 'GT (Guatemala)' , flagCode: 'gt' },
 { value: 'GN', label: 'GN (Guinea)' , flagCode: 'gn' },
 { value: 'GY', label: 'GY (Guyana)' , flagCode: 'gy' },
 { value: 'HT', label: 'HT (Haiti)' , flagCode: 'ht' },
 { value: 'HN', label: 'HN (Honduras)' , flagCode: 'hn' },
 { value: 'HU', label: 'HU (Hungary)' , flagCode: 'hu' },
 { value: 'IS', label: 'IS (Iceland)' , flagCode: 'is' },
 { value: 'IN', label: 'IN (India)' , flagCode: 'in' },
 { value: 'ID', label: 'ID (Indonesia)' , flagCode: 'id' },
 { value: 'IR', label: 'IR (Iran)' , flagCode: 'ir' },
 { value: 'IQ', label: 'IQ (Iraq)' , flagCode: 'iq' },
 { value: 'IE', label: 'IE (Ireland)' , flagCode: 'ie' },
 { value: 'IL', label: 'IL (Israel)' , flagCode: 'il' },
 { value: 'IT', label: 'IT (Italy)' , flagCode: 'it' },
 { value: 'JM', label: 'JM (Jamaica)' , flagCode: 'jm' },
 { value: 'JP', label: 'JP (Japan)' , flagCode: 'jp' },
 { value: 'JO', label: 'JO (Jordan)' , flagCode: 'jo' },
 { value: 'KZ', label: 'KZ (Kazakhstan)' , flagCode: 'kz' },
 { value: 'KE', label: 'KE (Kenya)' , flagCode: 'ke' },
 { value: 'KI', label: 'KI (Kiribati)' , flagCode: 'ki' },
 { value: 'KP', label: 'KP (North Korea)' , flagCode: 'kp' },
 { value: 'KR', label: 'KR (South Korea)' , flagCode: 'kr' },
 { value: 'KW', label: 'KW (Kuwait)' , flagCode: 'kw' },
 { value: 'KG', label: 'KG (Kyrgyzstan)' , flagCode: 'kg' },
 { value: 'LA', label: 'LA (Laos)' , flagCode: 'la' },
 { value: 'LV', label: 'LV (Latvia)' , flagCode: 'lv' },
 { value: 'LB', label: 'LB (Lebanon)' , flagCode: 'lb' },
 { value: 'LS', label: 'LS (Lesotho)' , flagCode: 'ls' },
 { value: 'LR', label: 'LR (Liberia)' , flagCode: 'lr' },
 { value: 'LY', label: 'LY (Libya)' , flagCode: 'ly' },
 { value: 'LI', label: 'LI (Liechtenstein)' , flagCode: 'li' },
 { value: 'LT', label: 'LT (Lithuania)' , flagCode: 'lt' },
 { value: 'LU', label: 'LU (Luxembourg)' , flagCode: 'lu' },
 { value: 'MG', label: 'MG (Madagascar)' , flagCode: 'mg' },
 { value: 'MW', label: 'MW (Malawi)' , flagCode: 'mw' },
 { value: 'MY', label: 'MY (Malaysia)' , flagCode: 'my' },
 { value: 'MV', label: 'MV (Maldives)' , flagCode: 'mv' },
 { value: 'ML', label: 'ML (Mali)' , flagCode: 'ml' },
 { value: 'MT', label: 'MT (Malta)' , flagCode: 'mt' },
 { value: 'MH', label: 'MH (Marshall Islands)' , flagCode: 'mh' },
 { value: 'MR', label: 'MR (Mauritania)' , flagCode: 'mr' },
 { value: 'MU', label: 'MU (Mauritius)' , flagCode: 'mu' },
 { value: 'MX', label: 'MX (Mexico)' , flagCode: 'mx' },
 { value: 'FM', label: 'FM (Micronesia)' , flagCode: 'fm' },
 { value: 'MD', label: 'MD (Moldova)' , flagCode: 'md' },
 { value: 'MC', label: 'MC (Monaco)' , flagCode: 'mc' },
 { value: 'MN', label: 'MN (Mongolia)' , flagCode: 'mn' },
 { value: 'ME', label: 'ME (Montenegro)' , flagCode: 'me' },
 { value: 'MA', label: 'MA (Morocco)' , flagCode: 'ma' },
 { value: 'MZ', label: 'MZ (Mozambique)' , flagCode: 'mz' },
 { value: 'MM', label: 'MM (Myanmar)' , flagCode: 'mm' },
 { value: 'NA', label: 'NA (Namibia)' , flagCode: 'na' },
 { value: 'NR', label: 'NR (Nauru)' , flagCode: 'nr' },
 { value: 'NP', label: 'NP (Nepal)' , flagCode: 'np' },
 { value: 'NL', label: 'NL (Netherlands)' , flagCode: 'nl' },
 { value: 'NZ', label: 'NZ (New Zealand)' , flagCode: 'nz' },
 { value: 'NI', label: 'NI (Nicaragua)' , flagCode: 'ni' },
 { value: 'NE', label: 'NE (Niger)' , flagCode: 'ne' },
 { value: 'NG', label: 'NG (Nigeria)' , flagCode: 'ng' },
 { value: 'NO', label: 'NO (Norway)' , flagCode: 'no' },
 { value: 'OM', label: 'OM (Oman)' , flagCode: 'om' },
 { value: 'PK', label: 'PK (Pakistan)' , flagCode: 'pk' },
 { value: 'PW', label: 'PW (Palau)' , flagCode: 'pw' },
 { value: 'PA', label: 'PA (Panama)' , flagCode: 'pa' },
 { value: 'PG', label: 'PG (Papua New Guinea)' , flagCode: 'pg' },
 { value: 'PY', label: 'PY (Paraguay)' , flagCode: 'py' },
 { value: 'PE', label: 'PE (Peru)' , flagCode: 'pe' },
 { value: 'PH', label: 'PH (Philippines)' , flagCode: 'ph' },
 { value: 'PL', label: 'PL (Poland)' , flagCode: 'pl' },
 { value: 'PT', label: 'PT (Portugal)' , flagCode: 'pt' },
 { value: 'QA', label: 'QA (Qatar)' , flagCode: 'qa' },
 { value: 'RO', label: 'RO (Romania)' , flagCode: 'ro' },
 { value: 'RU', label: 'RU (Russia)' , flagCode: 'ru' },
 { value: 'RW', label: 'RW (Rwanda)' , flagCode: 'rw' },
 { value: 'KN', label: 'KN (Saint Kitts and Nevis)' , flagCode: 'kn' },
 { value: 'LC', label: 'LC (Saint Lucia)' , flagCode: 'lc' },
 { value: 'VC', label: 'VC (Saint Vincent and the Grenadines)' , flagCode: 'vc' },
 { value: 'WS', label: 'WS (Samoa)' , flagCode: 'ws' },
 { value: 'SM', label: 'SM (San Marino)' , flagCode: 'sm' },
 { value: 'ST', label: 'ST (Sao Tome and Principe)' , flagCode: 'st' },
 { value: 'SA', label: 'SA (Saudi Arabia)' , flagCode: 'sa' },
 { value: 'SN', label: 'SN (Senegal)' , flagCode: 'sn' },
 { value: 'RS', label: 'RS (Serbia)' , flagCode: 'rs' },
 { value: 'SC', label: 'SC (Seychelles)' , flagCode: 'sc' },
 { value: 'SL', label: 'SL (Sierra Leone)' , flagCode: 'sl' },
 { value: 'SG', label: 'SG (Singapore)' , flagCode: 'sg' },
 { value: 'SK', label: 'SK (Slovakia)' , flagCode: 'sk' },
 { value: 'SI', label: 'SI (Slovenia)' , flagCode: 'si' },
 { value: 'SB', label: 'SB (Solomon Islands)' , flagCode: 'sb' },
 { value: 'SO', label: 'SO (Somalia)' , flagCode: 'so' },
 { value: 'ZA', label: 'ZA (South Africa)' , flagCode: 'za' },
 { value: 'ES', label: 'ES (Spain)' , flagCode: 'es' },
 { value: 'LK', label: 'LK (Sri Lanka)' , flagCode: 'lk' },
 { value: 'SD', label: 'SD (Sudan)' , flagCode: 'sd' },
 { value: 'SR', label: 'SR (Suriname)' , flagCode: 'sr' },
 { value: 'SE', label: 'SE (Sweden)' , flagCode: 'se' },
 { value: 'CH', label: 'CH (Switzerland)' , flagCode: 'ch' },
 { value: 'SY', label: 'SY (Syria)' , flagCode: 'sy' },
 { value: 'TJ', label: 'TJ (Tajikistan)' , flagCode: 'tj' },
 { value: 'TZ', label: 'TZ (Tanzania)' , flagCode: 'tz' },
 { value: 'TH', label: 'TH (Thailand)' , flagCode: 'th' },
 { value: 'TL', label: 'TL (Timor-Leste)' , flagCode: 'tl' },
 { value: 'TG', label: 'TG (Togo)' , flagCode: 'tg' },
 { value: 'TO', label: 'TO (Tonga)' , flagCode: 'to' },
 { value: 'TT', label: 'TT (Trinidad and Tobago)' , flagCode: 'tt' },
 { value: 'TN', label: 'TN (Tunisia)' , flagCode: 'tn' },
 { value: 'TR', label: 'TR (Turkey)' , flagCode: 'tr' },
 { value: 'TM', label: 'TM (Turkmenistan)' , flagCode: 'tm' },
 { value: 'TV', label: 'TV (Tuvalu)' , flagCode: 'tv' },
 { value: 'UG', label: 'UG (Uganda)' , flagCode: 'ug' },
 { value: 'UA', label: 'UA (Ukraine)' , flagCode: 'ua' },
 { value: 'AE', label: 'AE (United Arab Emirates)' , flagCode: 'ae' },
 { value: 'GB', label: 'GB (United Kingdom)' , flagCode: 'gb' },
 { value: 'US', label: 'US (United States)' , flagCode: 'us' },
 { value: 'UY', label: 'UY (Uruguay)' , flagCode: 'uy' },
 { value: 'UZ', label: 'UZ (Uzbekistan)' , flagCode: 'uz' },
 { value: 'VU', label: 'VU (Vanuatu)' , flagCode: 'vu' },
 { value: 'VE', label: 'VE (Venezuela)' , flagCode: 've' },
 { value: 'VN', label: 'VN (Vietnam)' , flagCode: 'vn' },
 { value: 'YE', label: 'YE (Yemen)' , flagCode: 'ye' },
 { value: 'ZM', label: 'ZM (Zambia)' , flagCode: 'zm' },
 { value: 'ZW', label: 'ZW (Zimbabwe)' , flagCode: 'zw' },
]

export function getFlagCode(country) {
  if (!country) return '';
  const clean = country.trim().toUpperCase();
  
  // Try exact match on value (e.g. 'AF')
  const byValue = countries.find(c => c.value === clean);
  if (byValue) return byValue.flagCode;

  // Try matching against the label (e.g. 'AF (Afghanistan)')
  const byLabel = countries.find(c => c.label.toUpperCase().includes(clean) || clean.toUpperCase().includes(c.label.toUpperCase()));
  if (byLabel) return byLabel.flagCode;

  // Try checking if country contains the value or label
  const fallback = countries.find(c => clean.includes(c.value));
  if (fallback) return fallback.flagCode;

  if (clean.length === 2) return clean.toLowerCase();
  return '';
}

export function cleanCountryLabel(country) {
  if (!country) return '';
  // Strip emojis from the string
  let cleaned = country.replace(/[\uE000-\uF8FF]|\uD83C[\uDC00-\uDFFF]|\uD83D[\uDC00-\uDFFF]|[\u2011-\u26FF]|\uD83E[\uDD10-\uDDFF]/g, '');
  // Normalize whitespace
  cleaned = cleaned.replace(/\s+/g, ' ').trim();
  // Remove empty parentheses if any (e.g. "AE () United Arab Emirates" -> "AE United Arab Emirates")
  cleaned = cleaned.replace(/\(\s*\)/g, '').replace(/\s+/g, ' ').trim();
  return cleaned;
}

